name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: fairdatause_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h postgres -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        echo "PostgreSQL is ready!"

    - name: Run backend tests
      run: npx vitest --config vitest.config.backend.ts --run --coverage
      env:
        NODE_ENV: test
        DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fairdatause_test
        TEST_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fairdatause_test

    - name: Run frontend tests
      run: npx vitest --config vitest.config.ts --run --coverage

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: coverage/